### ISSUE TITLE
[BUG报告] 玩家退出后，插件角色会保留

### ISSUE THREAD

**Issue by Pro845627** [CdcpServerDevelopmentTeam/CdcpServerDataCenter#2]

**Comment by zhaguanyang** [comment]
https://github.com/CdcpServerDevelopmentTeam/CdcpServerCorePlugin/commit/5c56917a3a34f6162cb5d0787bef96bf1249c930

**Comment by zhaguanyang** [comment]
https://github.com/CdcpServerDevelopmentTeam/CdcpServerCorePlugin/blob/274c073a3fdee5b54ee88122a6f0b7b7ce1132ff/SCPPlugin/PlayerData/SqlDatabase.cs#L621-L647
里面的
https://github.com/CdcpServerDevelopmentTeam/CdcpServerCorePlugin/blob/274c073a3fdee5b54ee88122a6f0b7b7ce1132ff/SCPPlugin/PlayerData/SqlDatabase.cs#L637
没有被call

已添加debug lines进一步确定原因
https://github.com/CdcpServerDevelopmentTeam/CdcpServerCorePlugin/blob/274c073a3fdee5b54ee88122a6f0b7b7ce1132ff/SCPPlugin/PlayerData/SqlDatabase.cs#L648-L651

**Comment by zhaguanyang** [comment]
已确定是由于``NextRoundPlayers``没有清空导致的

**Comment by zhaguanyang** [comment]
https://github.com/CdcpServerDevelopmentTeam/CdcpServerCorePlugin/commit/6827b05f7b63d2b3d3c862a50b5295d88e9b23ed
