### ISSUE TITLE
[BUG报告] 2419拿到可乐、死亡后变出的小僵尸只有100血

### ISSUE THREAD

**Issue by NimberLightning** [CdcpServerDevelopmentTeam/CdcpServerDataCenter#7]
**你当时的角色**：2419
**你的Steam昵称**：霓霆快雨，片刻即晴
*具体发生情况**：地表事件刷出一瓶可乐，喝过之后被捆绑，跑过逃生门后返回被枪杀，变成小僵尸只有100血

**Comment by Pro845627** [comment]
这是正常情况之外的问题，一般人不会这么做，几率太小了没必要
