### ISSUE TITLE
[BUG报告] 混沌分裂者兵种与官方翻译不一致

### ISSUE THREAD

**Issue by NimberLightning** [CdcpServerDevelopmentTeam/CdcpServerDataCenter#8]
混沌掠夺者应改为混沌压制者
混沌压制者应改为混沌掠夺者
逃生后的dd应改为混沌征召兵

**Comment by zhaguanyang** [comment]
> 混沌掠夺者应改为混沌压制者
混沌压制者应改为混沌掠夺者

这是游戏自身的翻译问题，已在纯净服测试。

> 逃生后的dd应改为混沌征召兵

测试时没有发生

**Comment by zhaguanyang** [comment]
其实不是翻译问题，是RA面板里面的两个兵种写反了
